/**
 * seed-concept-graph — MVP-3 knowledge-graph loader.
 *
 * Upserts the authored concept ladders (`CONCEPTS`) and their prerequisite
 * edges (`PREREQUISITES`) into the graph tables. Idempotent: safe to call
 * repeatedly, it never deletes and never rewrites human annotations in
 * `concept_video_segments`.
 *
 * Auth: admin JWT, or `X-Cron-Secret: $CRON_SECRET` for automated runs.
 * The data lives in `./data.ts`, generated by `scripts/seed-concepts.mjs`.
 */
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "npm:@supabase/supabase-js@2/cors";
import { getCallerUserId } from "../_shared/entitlements.ts";
import { CONCEPTS, PREREQUISITES } from "./data.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);

  const service = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });

  // ---- authorize: cron secret or admin role ----
  const cronSecret = req.headers.get("x-cron-secret");
  const expected = Deno.env.get("CRON_SECRET") ?? "";
  let authorized = Boolean(expected) && cronSecret === expected;
  if (!authorized) {
    const userId = await getCallerUserId(req).catch(() => null);
    if (!userId) return json({ error: "auth_required" }, 401);
    const { data: isAdmin } = await service.rpc("has_role", { _user_id: userId, _role: "admin" });
    authorized = Boolean(isAdmin);
  }
  if (!authorized) return json({ error: "forbidden" }, 403);

  try {
    // ---- concepts ----
    let conceptsUpserted = 0;
    for (let i = 0; i < CONCEPTS.length; i += 100) {
      const batch = CONCEPTS.slice(i, i + 100);
      const { error } = await service.from("concepts").upsert(batch, { onConflict: "slug" });
      if (error) throw new Error(`concepts batch ${i}: ${error.message}`);
      conceptsUpserted += batch.length;
    }

    // ---- resolve slugs → ids for the edges ----
    const idBySlug = new Map<string, string>();
    for (let i = 0; i < CONCEPTS.length; i += 500) {
      const slugs = CONCEPTS.slice(i, i + 500).map((c) => c.slug);
      const { data, error } = await service.from("concepts").select("id, slug").in("slug", slugs);
      if (error) throw new Error(`slug lookup: ${error.message}`);
      for (const row of data ?? []) idBySlug.set(row.slug as string, row.id as string);
    }

    const edgeRows = PREREQUISITES.flatMap((e) => {
      const concept_id = idBySlug.get(e.concept);
      const prerequisite_id = idBySlug.get(e.prerequisite);
      if (!concept_id || !prerequisite_id || concept_id === prerequisite_id) return [];
      return [{ concept_id, prerequisite_id, strength: e.strength }];
    });

    let edgesUpserted = 0;
    for (let i = 0; i < edgeRows.length; i += 100) {
      const batch = edgeRows.slice(i, i + 100);
      const { error } = await service
        .from("concept_prerequisites")
        .upsert(batch, { onConflict: "concept_id,prerequisite_id", ignoreDuplicates: true });
      if (error) throw new Error(`prerequisites batch ${i}: ${error.message}`);
      edgesUpserted += batch.length;
    }

    const { data: stats } = await service.rpc("get_concept_graph_stats");

    return json({ ok: true, conceptsUpserted, edgesUpserted, stats });
  } catch (e) {
    console.error("[seed-concept-graph]", e);
    return json({ error: "seed_failed", message: (e as Error).message }, 500);
  }
});
