// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return the signed-in Heartify user's profile (display name, locale, timezone, preferred reciter).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("profiles").select("display_name, handle, bio, country_code, timezone, preferred_locale, preferred_reciter, onboarding_completed_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null, email: ctx.getUserEmail() ?? null }
    };
  }
});

// src/lib/mcp/tools/get-streak.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_streak_default = defineTool2({
  name: "get_streak",
  title: "Get daily-dose streak",
  description: "Return the signed-in user's current streak, longest streak, and total daily doses completed.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("streaks").select("current_streak, longest_streak, total_doses_completed, last_completed_date").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const row = data ?? { current_streak: 0, longest_streak: 0, total_doses_completed: 0, last_completed_date: null };
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: { streak: row }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_favorites_default = defineTool3({
  name: "list_favorites",
  title: "List favorites",
  description: "List the signed-in user's favorited Heartify videos (most recent first).",
  inputSchema: { limit: z.number().int().min(1).max(100).default(25).describe("How many favorites to return.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("favorites").select("video_id, video_title, channel_title, thumbnail_url, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-dhikr.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_dhikr_default = defineTool4({
  name: "log_dhikr_session",
  title: "Log a dhikr session",
  description: "Record a dhikr (remembrance) session for the signed-in user. Use for tasbih counts like SubhanAllah, Alhamdulillah, Allahu Akbar.",
  inputSchema: {
    dhikr_key: z2.string().min(1).describe("Dhikr identifier, e.g. 'subhanallah', 'alhamdulillah', 'allahu-akbar'."),
    count: z2.number().int().min(1).max(1e4).describe("Number of repetitions completed."),
    target: z2.number().int().min(1).max(1e4).nullable().default(null).describe("Optional target count for the session.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ dhikr_key, count, target }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("dhikr_sessions").insert({
      user_id: ctx.getUserId(),
      dhikr_key,
      count,
      target,
      source: "mcp",
      completed_at: (/* @__PURE__ */ new Date()).toISOString()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${count}\xD7 ${dhikr_key}.` }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/tools/log-salah.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_salah_default = defineTool5({
  name: "log_salah",
  title: "Log a prayer (salah)",
  description: "Record a completed prayer for the signed-in user.",
  inputSchema: {
    prayer: z3.enum(["fajr", "dhuhr", "asr", "maghrib", "isha"]).describe("Which of the five daily prayers."),
    prayer_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Prayer date in YYYY-MM-DD."),
    on_time: z3.boolean().default(true).describe("Whether the prayer was prayed on time."),
    notes: z3.string().max(500).nullable().default(null).describe("Optional short notes.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ prayer, prayer_date, on_time, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("salah_log").insert({
      user_id: ctx.getUserId(),
      prayer,
      prayer_date,
      on_time,
      notes,
      prayed_at: (/* @__PURE__ */ new Date()).toISOString(),
      source: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${prayer} for ${prayer_date}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/prayer-times.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";
var prayer_times_default = defineTool6({
  name: "get_prayer_times",
  title: "Get prayer times",
  description: "Return today's five daily prayer times for a location. Uses Heartify's public prayer-times endpoint.",
  inputSchema: {
    lat: z4.number().min(-90).max(90).describe("Latitude in decimal degrees."),
    lng: z4.number().min(-180).max(180).describe("Longitude in decimal degrees."),
    date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().default(null).describe("Date YYYY-MM-DD (defaults to today)."),
    method: z4.enum(["MWL", "ISNA", "Egypt", "Makkah", "Karachi", "Tehran", "Jafari"]).default("MWL").describe("Calculation method.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ lat, lng, date, method }) => {
    const base = process.env.SUPABASE_URL;
    if (!base) return { content: [{ type: "text", text: "SUPABASE_URL not configured" }], isError: true };
    const url = new URL(`${base}/functions/v1/prayer-times`);
    url.searchParams.set("lat", String(lat));
    url.searchParams.set("lng", String(lng));
    url.searchParams.set("method", method);
    if (date) url.searchParams.set("date", date);
    const res = await fetch(url.toString());
    const text = await res.text();
    if (!res.ok) return { content: [{ type: "text", text: `Upstream ${res.status}: ${text}` }], isError: true };
    let json;
    try {
      json = JSON.parse(text);
    } catch {
      json = text;
    }
    return {
      content: [{ type: "text", text: typeof json === "string" ? json : JSON.stringify(json, null, 2) }],
      structuredContent: { times: json }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tbgxtwgliumqqtuppztu";
var mcp_default = defineMcp({
  name: "heartify-mcp",
  title: "Heartify",
  version: "0.1.0",
  instructions: "Tools for Heartify \u2014 a scholar-moderated Islamic content and worship-tracking app. Use `get_profile` and `get_streak` to read the signed-in user's account, `list_favorites` for their saved videos, `log_dhikr_session` and `log_salah` to record acts of worship, and `get_prayer_times` for salah timings by location.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_streak_default, list_favorites_default, log_dhikr_default, log_salah_default, prayer_times_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
