INSERT INTO public.event_schemas(event_name, description, required_properties) VALUES
  ('acquisition.visited','Session or page landing with optional referrer', ARRAY['path']),
  ('acquisition.signed_up','New account created via provider', ARRAY['method']),
  ('activation.onboarding_started','User opened onboarding wizard', ARRAY[]::text[]),
  ('activation.onboarding_completed','User completed onboarding wizard', ARRAY['interest_count']),
  ('activation.first_video_played','User played their first video', ARRAY['video_id']),
  ('activation.first_favorite','User favorited their first item', ARRAY['video_id']),
  ('search.issued','Search executed with sanitized query length only', ARRAY['query_len','result_count']),
  ('search.no_results','Search returned zero results', ARRAY['query_len']),
  ('search.result_clicked','Search result opened', ARRAY['query_len','video_id','position']),
  ('recommendation.impression','Recommendation shown', ARRAY['video_id','source']),
  ('recommendation.clicked','Recommendation opened', ARRAY['video_id','source','position']),
  ('recommendation.dismissed','Recommendation dismissed / not interested', ARRAY['video_id','source']),
  ('favorites.added','Item added to favorites', ARRAY['video_id']),
  ('favorites.removed','Item removed from favorites', ARRAY['video_id']),
  ('premium.surface_viewed','Premium upsell surface viewed', ARRAY['surface']),
  ('premium.upgrade_clicked','Premium CTA clicked', ARRAY['surface']),
  ('premium.purchased','Premium plan purchased', ARRAY['plan','amount_usd']),
  ('referral.link_copied','Referral link copied', ARRAY['channel']),
  ('referral.invited','Referral link shared via native share sheet', ARRAY['channel']),
  ('referral.redeemed','Referral code redeemed', ARRAY['code_len']),
  ('retention.daily_dose_completed','User completed their Daily Dose', ARRAY['day_offset']),
  ('retention.streak_extended','Streak length incremented', ARRAY['length']),
  ('audit_page_view','Admin opened audit dashboard', ARRAY[]::text[]),
  ('audit_run_started','Admin started audit run', ARRAY[]::text[]),
  ('audit_run_completed','Audit run finished', ARRAY[]::text[]),
  ('audit_run_failed','Audit run errored', ARRAY[]::text[]),
  ('admin_pattern_blocked','Admin blocked a moderation pattern', ARRAY[]::text[]),
  ('admin_pattern_unblocked','Admin unblocked a moderation pattern', ARRAY[]::text[]),
  ('moderation_log_view','Admin opened moderation log', ARRAY[]::text[]),
  ('moderation_log_loaded','Moderation log fetch succeeded', ARRAY[]::text[]),
  ('moderation_log_load_failed','Moderation log fetch failed', ARRAY[]::text[]),
  ('khatm_group_created','User created a group khatm', ARRAY[]::text[]),
  ('khatm_group_joined','User joined a group khatm', ARRAY[]::text[]),
  ('khatm_group_joined_via_link','User joined a group khatm via invite link', ARRAY[]::text[]),
  ('khatm_invite_copied','User copied group khatm invite link', ARRAY[]::text[]),
  ('khatm_invite_shared','User shared group khatm invite', ARRAY[]::text[]),
  ('khatm_juz_claimed','User claimed a juz in a group khatm', ARRAY[]::text[]),
  ('khatm_juz_completed','User completed a claimed juz', ARRAY[]::text[]),
  ('referral_link_copied','Referral link copied (legacy alias)', ARRAY[]::text[]),
  ('referral_link_shared','Referral link shared (legacy alias)', ARRAY[]::text[]),
  ('streak_activity_recorded','A streak-eligible activity was recorded', ARRAY[]::text[]),
  ('perf','Client-reported performance sample', ARRAY[]::text[])
ON CONFLICT (event_name) DO UPDATE
  SET description = EXCLUDED.description,
      required_properties = EXCLUDED.required_properties;