-- Native-language, high-priority discovery queries for South Asian launch markets.
-- Halal moderation (halalGuard + SQL deny patterns + visual sweep) still gates every candidate.
INSERT INTO public.discovery_topic_queries (language, topic, query, priority, enabled, origin)
VALUES
-- ===== Bengali =====
('bn','islamic','কুরআনের তাফসীর বাংলা',100,true,'local_first_bn'),
('bn','islamic','হাদিসের ব্যাখ্যা বাংলা',100,true,'local_first_bn'),
('bn','islamic','সীরাতুন্নবী আলোচনা',100,true,'local_first_bn'),
('bn','islamic','ইসলামিক প্রশ্ন উত্তর',100,true,'local_first_bn'),
('bn','islamic','ফিকহ মাসআলা বাংলা',100,true,'local_first_bn'),
('bn','islamic','আকীদা আলোচনা বাংলা',100,true,'local_first_bn'),
('bn','islamic','নামাজ শিক্ষা বাংলা',100,true,'local_first_bn'),
('bn','islamic','রোজার মাসআলা বাংলা',100,true,'local_first_bn'),
('bn','islamic','হজ ও উমরাহ নির্দেশিকা বাংলা',100,true,'local_first_bn'),
('bn','islamic','যাকাত হিসাব বাংলা',100,true,'local_first_bn'),
('bn','islamic','দুআ ও যিকির শিক্ষা বাংলা',100,true,'local_first_bn'),
('bn','islamic','ইসলামিক আলোচনা মাহফিল',98,true,'local_first_bn'),
('bn','quran','কুরআন শিক্ষা কোর্স বাংলা',100,true,'local_first_bn'),
('bn','quran','তাজবীদ শিক্ষা বাংলা',100,true,'local_first_bn'),
('bn','quran','আরবি ব্যাকরণ শিক্ষা বাংলা',100,true,'local_first_bn'),
('bn','quran','কুরআনের শব্দ শিক্ষা বাংলা',100,true,'local_first_bn'),
('bn','history','ইসলামের ইতিহাস আলোচনা',100,true,'local_first_bn'),
('bn','history','বাংলাদেশের ইতিহাস ডকুমেন্টারি',98,true,'local_first_bn'),
('bn','history','বিশ্ব ইতিহাস বাংলা ব্যাখ্যা',96,true,'local_first_bn'),
('bn','history','উসমানীয় সাম্রাজ্যের ইতিহাস বাংলা',96,true,'local_first_bn'),
('bn','science','বিজ্ঞান ব্যাখ্যা বাংলা',98,true,'local_first_bn'),
('bn','science','পদার্থবিজ্ঞান ক্লাস বাংলা',96,true,'local_first_bn'),
('bn','science','রসায়ন ক্লাস বাংলা',96,true,'local_first_bn'),
('bn','science','জীববিজ্ঞান ক্লাস বাংলা',96,true,'local_first_bn'),
('bn','science','মহাকাশ বিজ্ঞান বাংলা',96,true,'local_first_bn'),
('bn','education','গণিত সমাধান বাংলা',98,true,'local_first_bn'),
('bn','education','এসএসসি প্রস্তুতি ক্লাস',98,true,'local_first_bn'),
('bn','education','এইচএসসি প্রস্তুতি ক্লাস',98,true,'local_first_bn'),
('bn','education','বিসিএস প্রস্তুতি ক্লাস',96,true,'local_first_bn'),
('bn','education','ভর্তি পরীক্ষা প্রস্তুতি বাংলা',96,true,'local_first_bn'),
('bn','education','ইংরেজি শেখা বাংলা টিউটোরিয়াল',96,true,'local_first_bn'),
('bn','tech','প্রোগ্রামিং শেখা বাংলা',98,true,'local_first_bn'),
('bn','tech','ওয়েব ডেভেলপমেন্ট বাংলা টিউটোরিয়াল',96,true,'local_first_bn'),
('bn','tech','ফ্রিল্যান্সিং শেখা বাংলা',96,true,'local_first_bn'),
('bn','tech','কম্পিউটার শিক্ষা বাংলা',94,true,'local_first_bn'),
('bn','tech','এআই ব্যাখ্যা বাংলা',94,true,'local_first_bn'),
('bn','business','উদ্যোক্তা পরামর্শ বাংলা',96,true,'local_first_bn'),
('bn','business','ইসলামী অর্থনীতি আলোচনা বাংলা',96,true,'local_first_bn'),
('bn','business','ব্যবসা শিক্ষা বাংলা',94,true,'local_first_bn'),
('bn','health','স্বাস্থ্য পরামর্শ ডাক্তার বাংলা',94,true,'local_first_bn'),
('bn','health','সুন্নাহ খাদ্য ও স্বাস্থ্য বাংলা',94,true,'local_first_bn'),
('bn','self_dev','আত্মউন্নয়ন বাংলা আলোচনা',94,true,'local_first_bn'),
('bn','self_dev','সময় ব্যবস্থাপনা বাংলা',94,true,'local_first_bn'),
('bn','family','সন্তান প্রতিপালন ইসলামিক আলোচনা',94,true,'local_first_bn'),
('bn','family','পারিবারিক জীবন ইসলামিক পরামর্শ',94,true,'local_first_bn'),
('bn','child_education','শিশুদের ইসলামিক শিক্ষা বাংলা',94,true,'local_first_bn'),
('bn','child_education','শিশুদের শিক্ষামূলক ভিডিও বাংলা',92,true,'local_first_bn'),
('bn','arabic','মাদরাসা পাঠ বাংলা',92,true,'local_first_bn'),
('bn','documentary','তথ্যচিত্র বাংলা শিক্ষামূলক',92,true,'local_first_bn'),
('bn','geography','ভূগোল ব্যাখ্যা বাংলা',90,true,'local_first_bn'),
-- ===== Urdu =====
('ur','islamic','قرآن کی تفسیر اردو',100,true,'local_first_ur'),
('ur','islamic','حدیث کی تشریح اردو',100,true,'local_first_ur'),
('ur','islamic','سیرت النبی بیان',100,true,'local_first_ur'),
('ur','islamic','اسلامی سوال جواب اردو',100,true,'local_first_ur'),
('ur','islamic','فقہ مسائل اردو',100,true,'local_first_ur'),
('ur','islamic','عقیدہ کا بیان اردو',100,true,'local_first_ur'),
('ur','islamic','نماز سیکھیں اردو',100,true,'local_first_ur'),
('ur','islamic','رمضان بیان اردو',100,true,'local_first_ur'),
('ur','islamic','زکوٰۃ کے مسائل اردو',98,true,'local_first_ur'),
('ur','islamic','حج و عمرہ رہنمائی اردو',98,true,'local_first_ur'),
('ur','islamic','دعا اور اذکار اردو',98,true,'local_first_ur'),
('ur','quran','قرآن پڑھنا سیکھیں اردو',100,true,'local_first_ur'),
('ur','quran','تجوید کورس اردو',100,true,'local_first_ur'),
('ur','quran','عربی گرامر اردو میں',98,true,'local_first_ur'),
('ur','history','اسلامی تاریخ اردو',100,true,'local_first_ur'),
('ur','history','خلافت عثمانیہ تاریخ اردو',96,true,'local_first_ur'),
('ur','history','پاکستان کی تاریخ دستاویزی',96,true,'local_first_ur'),
('ur','science','سائنس کی وضاحت اردو',98,true,'local_first_ur'),
('ur','science','فزکس لیکچر اردو',96,true,'local_first_ur'),
('ur','science','کیمسٹری لیکچر اردو',96,true,'local_first_ur'),
('ur','science','بیالوجی لیکچر اردو',96,true,'local_first_ur'),
('ur','education','ریاضی حل اردو',98,true,'local_first_ur'),
('ur','education','میٹرک تیاری لیکچر',96,true,'local_first_ur'),
('ur','education','ایف ایس سی لیکچر اردو',96,true,'local_first_ur'),
('ur','education','سی ایس ایس تیاری لیکچر',94,true,'local_first_ur'),
('ur','education','انگریزی سیکھیں اردو میں',96,true,'local_first_ur'),
('ur','tech','پروگرامنگ سیکھیں اردو',98,true,'local_first_ur'),
('ur','tech','فری لانسنگ سیکھیں اردو',96,true,'local_first_ur'),
('ur','tech','کمپیوٹر کورس اردو',94,true,'local_first_ur'),
('ur','tech','مصنوعی ذہانت اردو وضاحت',94,true,'local_first_ur'),
('ur','business','کاروبار کے مشورے اردو',96,true,'local_first_ur'),
('ur','business','اسلامی معاشیات اردو',96,true,'local_first_ur'),
('ur','health','صحت کے مشورے ڈاکٹر اردو',94,true,'local_first_ur'),
('ur','self_dev','خود سازی اردو لیکچر',94,true,'local_first_ur'),
('ur','family','تربیت اولاد اسلامی اردو',94,true,'local_first_ur'),
('ur','child_education','بچوں کی اسلامی تعلیم اردو',94,true,'local_first_ur'),
('ur','documentary','معلوماتی دستاویزی فلم اردو',92,true,'local_first_ur'),
-- ===== Hindi =====
('hi','islamic','कुरान की तफ़सीर हिंदी',100,true,'local_first_hi'),
('hi','islamic','हदीस की व्याख्या हिंदी',100,true,'local_first_hi'),
('hi','islamic','सीरत नबी बयान हिंदी',100,true,'local_first_hi'),
('hi','islamic','इस्लामिक सवाल जवाब हिंदी',100,true,'local_first_hi'),
('hi','islamic','नमाज़ सीखें हिंदी',100,true,'local_first_hi'),
('hi','islamic','रमज़ान बयान हिंदी',98,true,'local_first_hi'),
('hi','islamic','फ़िक़्ह मसाइल हिंदी',98,true,'local_first_hi'),
('hi','quran','कुरान पढ़ना सीखें हिंदी',100,true,'local_first_hi'),
('hi','quran','तजवीद कोर्स हिंदी',98,true,'local_first_hi'),
('hi','quran','अरबी व्याकरण हिंदी में',96,true,'local_first_hi'),
('hi','history','इस्लामी इतिहास हिंदी',98,true,'local_first_hi'),
('hi','history','विश्व इतिहास हिंदी डॉक्यूमेंट्री',96,true,'local_first_hi'),
('hi','science','विज्ञान समझाया हिंदी',98,true,'local_first_hi'),
('hi','science','भौतिक विज्ञान लेक्चर हिंदी',96,true,'local_first_hi'),
('hi','science','रसायन विज्ञान लेक्चर हिंदी',96,true,'local_first_hi'),
('hi','science','जीव विज्ञान लेक्चर हिंदी',96,true,'local_first_hi'),
('hi','education','गणित समाधान हिंदी',98,true,'local_first_hi'),
('hi','education','यूपीएससी तैयारी लेक्चर',96,true,'local_first_hi'),
('hi','education','बोर्ड परीक्षा तैयारी हिंदी',96,true,'local_first_hi'),
('hi','education','अंग्रेज़ी सीखें हिंदी में',96,true,'local_first_hi'),
('hi','tech','प्रोग्रामिंग सीखें हिंदी',98,true,'local_first_hi'),
('hi','tech','फ्रीलांसिंग सीखें हिंदी',94,true,'local_first_hi'),
('hi','tech','आर्टिफिशियल इंटेलिजेंस हिंदी',94,true,'local_first_hi'),
('hi','business','व्यापार सलाह हिंदी',94,true,'local_first_hi'),
('hi','business','इस्लामी अर्थव्यवस्था हिंदी',94,true,'local_first_hi'),
('hi','health','स्वास्थ्य सलाह डॉक्टर हिंदी',94,true,'local_first_hi'),
('hi','self_dev','आत्म विकास हिंदी लेक्चर',94,true,'local_first_hi'),
('hi','family','बच्चों की परवरिश इस्लामी हिंदी',94,true,'local_first_hi'),
('hi','child_education','बच्चों की इस्लामी शिक्षा हिंदी',94,true,'local_first_hi'),
('hi','documentary','शैक्षिक डॉक्यूमेंट्री हिंदी',92,true,'local_first_hi')
ON CONFLICT (language, query) DO UPDATE
  SET priority = GREATEST(public.discovery_topic_queries.priority, EXCLUDED.priority),
      enabled = true,
      topic = EXCLUDED.topic,
      updated_at = now();
