
-- ============================================================
-- Phase 5: Experimentation Framework
-- ============================================================

-- Experiment status enum
DO $$ BEGIN
  CREATE TYPE public.experiment_status AS ENUM ('draft','running','paused','completed','archived');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- experiments
CREATE TABLE IF NOT EXISTS public.experiments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  status public.experiment_status NOT NULL DEFAULT 'draft',
  traffic_allocation numeric NOT NULL DEFAULT 1.0 CHECK (traffic_allocation >= 0 AND traffic_allocation <= 1),
  primary_metric text,
  audience_rules jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz,
  ended_at timestamptz,
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.experiments TO authenticated, anon;
GRANT ALL ON public.experiments TO service_role;
ALTER TABLE public.experiments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "experiments readable by all" ON public.experiments FOR SELECT USING (true);
CREATE POLICY "experiments admin write" ON public.experiments FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

-- experiment_variants
CREATE TABLE IF NOT EXISTS public.experiment_variants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL REFERENCES public.experiments(id) ON DELETE CASCADE,
  key text NOT NULL,
  weight numeric NOT NULL DEFAULT 0.5 CHECK (weight >= 0 AND weight <= 1),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_control boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (experiment_id, key)
);
GRANT SELECT ON public.experiment_variants TO authenticated, anon;
GRANT ALL ON public.experiment_variants TO service_role;
ALTER TABLE public.experiment_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "variants readable by all" ON public.experiment_variants FOR SELECT USING (true);
CREATE POLICY "variants admin write" ON public.experiment_variants FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

-- variant_assignments (sticky per user or anon key)
CREATE TABLE IF NOT EXISTS public.variant_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL REFERENCES public.experiments(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  anon_key text,
  variant_key text NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (experiment_id, user_id),
  UNIQUE (experiment_id, anon_key),
  CHECK (user_id IS NOT NULL OR anon_key IS NOT NULL)
);
GRANT SELECT, INSERT ON public.variant_assignments TO authenticated;
GRANT SELECT, INSERT ON public.variant_assignments TO anon;
GRANT ALL ON public.variant_assignments TO service_role;
ALTER TABLE public.variant_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "assignments read own" ON public.variant_assignments FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.has_role(auth.uid(),'admin'));
CREATE POLICY "assignments read own anon" ON public.variant_assignments FOR SELECT TO anon
  USING (user_id IS NULL);
CREATE POLICY "assignments insert self" ON public.variant_assignments FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() OR user_id IS NULL);
CREATE POLICY "assignments insert anon" ON public.variant_assignments FOR INSERT TO anon
  WITH CHECK (user_id IS NULL AND anon_key IS NOT NULL);

-- experiment_exposures
CREATE TABLE IF NOT EXISTS public.experiment_exposures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experiment_id uuid NOT NULL REFERENCES public.experiments(id) ON DELETE CASCADE,
  variant_key text NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  anon_key text,
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_exposures_exp_time ON public.experiment_exposures(experiment_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_exposures_user ON public.experiment_exposures(user_id) WHERE user_id IS NOT NULL;
GRANT INSERT ON public.experiment_exposures TO authenticated, anon;
GRANT SELECT ON public.experiment_exposures TO authenticated;
GRANT ALL ON public.experiment_exposures TO service_role;
ALTER TABLE public.experiment_exposures ENABLE ROW LEVEL SECURITY;
CREATE POLICY "exposures admin read" ON public.experiment_exposures FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(),'admin'));
CREATE POLICY "exposures insert self" ON public.experiment_exposures FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() OR user_id IS NULL);
CREATE POLICY "exposures insert anon" ON public.experiment_exposures FOR INSERT TO anon
  WITH CHECK (user_id IS NULL);

-- experiment_guardrails
CREATE TABLE IF NOT EXISTS public.experiment_guardrails (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL REFERENCES public.experiments(id) ON DELETE CASCADE,
  metric text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('increase','decrease','either')),
  threshold numeric NOT NULL,
  triggered boolean NOT NULL DEFAULT false,
  triggered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.experiment_guardrails TO authenticated;
GRANT ALL ON public.experiment_guardrails TO service_role;
ALTER TABLE public.experiment_guardrails ENABLE ROW LEVEL SECURITY;
CREATE POLICY "guardrails admin" ON public.experiment_guardrails FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

-- ============================================================
-- Event schema catalog
-- ============================================================
CREATE TABLE IF NOT EXISTS public.event_schemas (
  event_name text PRIMARY KEY,
  description text,
  required_properties text[] NOT NULL DEFAULT '{}',
  property_types jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.event_schemas TO authenticated, anon;
GRANT ALL ON public.event_schemas TO service_role;
ALTER TABLE public.event_schemas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "event_schemas read" ON public.event_schemas FOR SELECT USING (true);
CREATE POLICY "event_schemas admin write" ON public.event_schemas FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

-- Seed core events
INSERT INTO public.event_schemas(event_name, description, required_properties) VALUES
  ('page_view','User loaded a page', ARRAY['path']),
  ('video_play','User started a video', ARRAY['video_id']),
  ('video_complete','User finished a video', ARRAY['video_id']),
  ('daily_dose_complete','User completed daily dose', ARRAY[]::text[]),
  ('signup','New account created', ARRAY[]::text[]),
  ('login','User signed in', ARRAY[]::text[]),
  ('experiment_exposure','Experiment variant shown', ARRAY['experiment_key','variant_key']),
  ('feature_flag_evaluated','Feature flag checked', ARRAY['flag_key','enabled']),
  ('search','User searched', ARRAY['query']),
  ('share','User shared content', ARRAY['kind'])
ON CONFLICT (event_name) DO NOTHING;

-- Validation trigger on analytics_events
CREATE OR REPLACE FUNCTION public.validate_analytics_event()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE
  sch RECORD;
  req text;
BEGIN
  SELECT * INTO sch FROM public.event_schemas WHERE event_name = NEW.event_name AND is_active = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'unknown_event: %', NEW.event_name USING ERRCODE = 'check_violation';
  END IF;
  IF array_length(sch.required_properties, 1) IS NOT NULL THEN
    FOREACH req IN ARRAY sch.required_properties LOOP
      IF NEW.properties IS NULL OR NOT (NEW.properties ? req) THEN
        RAISE EXCEPTION 'missing_required_property: % for event %', req, NEW.event_name USING ERRCODE = 'check_violation';
      END IF;
    END LOOP;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_validate_analytics_event ON public.analytics_events;
CREATE TRIGGER trg_validate_analytics_event
  BEFORE INSERT ON public.analytics_events
  FOR EACH ROW EXECUTE FUNCTION public.validate_analytics_event();

-- ============================================================
-- Cohorts
-- ============================================================
CREATE TABLE IF NOT EXISTS public.user_cohorts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  rules jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.user_cohorts TO authenticated;
GRANT ALL ON public.user_cohorts TO service_role;
ALTER TABLE public.user_cohorts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cohorts admin" ON public.user_cohorts FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "cohorts read authed" ON public.user_cohorts FOR SELECT TO authenticated USING (true);

CREATE TABLE IF NOT EXISTS public.user_cohort_members (
  cohort_id uuid NOT NULL REFERENCES public.user_cohorts(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  added_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (cohort_id, user_id)
);
GRANT SELECT ON public.user_cohort_members TO authenticated;
GRANT ALL ON public.user_cohort_members TO service_role;
ALTER TABLE public.user_cohort_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cohort_members admin" ON public.user_cohort_members FOR ALL TO authenticated
  USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "cohort_members self read" ON public.user_cohort_members FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.is_in_cohort(_user_id uuid, _cohort_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_cohort_members WHERE user_id = _user_id AND cohort_id = _cohort_id)
$$;

-- ============================================================
-- Feature flag targeting extensions
-- ============================================================
ALTER TABLE public.feature_flags
  ADD COLUMN IF NOT EXISTS kill_switch boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS cohort_id uuid REFERENCES public.user_cohorts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS targeting_rules jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE OR REPLACE FUNCTION public.evaluate_feature_flag(_key text, _user_id uuid)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  f RECORD;
  bucket int;
BEGIN
  SELECT * INTO f FROM public.feature_flags WHERE key = _key;
  IF NOT FOUND THEN RETURN false; END IF;
  IF f.kill_switch THEN RETURN false; END IF;
  IF NOT f.enabled THEN RETURN false; END IF;
  IF f.cohort_id IS NOT NULL THEN
    IF _user_id IS NULL OR NOT public.is_in_cohort(_user_id, f.cohort_id) THEN
      RETURN false;
    END IF;
  END IF;
  IF f.rollout_percent >= 100 THEN RETURN true; END IF;
  IF f.rollout_percent <= 0 THEN RETURN false; END IF;
  bucket := abs(hashtext(_key || COALESCE(_user_id::text, ''))) % 100;
  RETURN bucket < f.rollout_percent;
END $$;

-- ============================================================
-- Sticky assignment RPC
-- ============================================================
CREATE OR REPLACE FUNCTION public.assign_experiment_variant(_experiment_key text, _anon_key text)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  exp RECORD;
  existing text;
  chosen text;
  bucket numeric;
  cum numeric := 0;
  v RECORD;
  uid uuid := auth.uid();
  seed text;
BEGIN
  SELECT * INTO exp FROM public.experiments WHERE key = _experiment_key AND status = 'running';
  IF NOT FOUND THEN RETURN NULL; END IF;

  IF uid IS NOT NULL THEN
    SELECT variant_key INTO existing FROM public.variant_assignments
      WHERE experiment_id = exp.id AND user_id = uid;
  ELSIF _anon_key IS NOT NULL THEN
    SELECT variant_key INTO existing FROM public.variant_assignments
      WHERE experiment_id = exp.id AND anon_key = _anon_key;
  END IF;
  IF existing IS NOT NULL THEN RETURN existing; END IF;

  seed := COALESCE(uid::text, _anon_key, gen_random_uuid()::text);
  -- traffic allocation gate
  IF (abs(hashtext(exp.key || ':traffic:' || seed)) % 10000) / 10000.0 > exp.traffic_allocation THEN
    RETURN NULL;
  END IF;

  bucket := (abs(hashtext(exp.key || ':' || seed)) % 10000) / 10000.0;
  FOR v IN SELECT key, weight FROM public.experiment_variants WHERE experiment_id = exp.id ORDER BY key LOOP
    cum := cum + v.weight;
    IF bucket < cum THEN chosen := v.key; EXIT; END IF;
  END LOOP;
  IF chosen IS NULL THEN
    SELECT key INTO chosen FROM public.experiment_variants WHERE experiment_id = exp.id ORDER BY key LIMIT 1;
  END IF;
  IF chosen IS NULL THEN RETURN NULL; END IF;

  INSERT INTO public.variant_assignments(experiment_id, user_id, anon_key, variant_key)
  VALUES (exp.id, uid, CASE WHEN uid IS NULL THEN _anon_key ELSE NULL END, chosen)
  ON CONFLICT DO NOTHING;

  RETURN chosen;
END $$;

GRANT EXECUTE ON FUNCTION public.assign_experiment_variant(text,text) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.evaluate_feature_flag(text,uuid) TO authenticated, anon;

-- ============================================================
-- Admin views
-- ============================================================
CREATE OR REPLACE VIEW public.admin_experiment_results
WITH (security_invoker = true) AS
SELECT
  e.id AS experiment_id,
  e.key AS experiment_key,
  e.status,
  ex.variant_key,
  count(*) AS exposures,
  count(DISTINCT COALESCE(ex.user_id::text, ex.anon_key)) AS unique_users
FROM public.experiments e
JOIN public.experiment_exposures ex ON ex.experiment_id = e.id
GROUP BY e.id, e.key, e.status, ex.variant_key;

GRANT SELECT ON public.admin_experiment_results TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_retention_cohorts()
RETURNS TABLE (
  cohort_week date,
  cohort_size bigint,
  d1 bigint,
  d7 bigint,
  d30 bigint
) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, auth AS $$
  WITH signups AS (
    SELECT u.id, date_trunc('week', u.created_at)::date AS cohort_week, u.created_at
    FROM auth.users u
    WHERE u.created_at > now() - interval '180 days'
  ),
  activity AS (
    SELECT user_id, date(created_at) AS d FROM public.analytics_events
    WHERE user_id IS NOT NULL AND created_at > now() - interval '210 days'
    GROUP BY user_id, date(created_at)
  )
  SELECT
    s.cohort_week,
    count(DISTINCT s.id) AS cohort_size,
    count(DISTINCT s.id) FILTER (WHERE a.d = date(s.created_at) + 1) AS d1,
    count(DISTINCT s.id) FILTER (WHERE a.d BETWEEN date(s.created_at) + 6 AND date(s.created_at) + 8) AS d7,
    count(DISTINCT s.id) FILTER (WHERE a.d BETWEEN date(s.created_at) + 28 AND date(s.created_at) + 32) AS d30
  FROM signups s
  LEFT JOIN activity a ON a.user_id = s.id
  GROUP BY s.cohort_week
  ORDER BY s.cohort_week DESC
$$;

REVOKE ALL ON FUNCTION public.admin_retention_cohorts() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_retention_cohorts() TO authenticated;

-- Wrap with admin check
CREATE OR REPLACE FUNCTION public.get_retention_cohorts()
RETURNS TABLE (cohort_week date, cohort_size bigint, d1 bigint, d7 bigint, d30 bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.has_role(auth.uid(),'admin') THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  RETURN QUERY SELECT * FROM public.admin_retention_cohorts();
END $$;

GRANT EXECUTE ON FUNCTION public.get_retention_cohorts() TO authenticated;

-- updated_at triggers
DROP TRIGGER IF EXISTS trg_experiments_updated_at ON public.experiments;
CREATE TRIGGER trg_experiments_updated_at BEFORE UPDATE ON public.experiments
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS trg_event_schemas_updated_at ON public.event_schemas;
CREATE TRIGGER trg_event_schemas_updated_at BEFORE UPDATE ON public.event_schemas
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS trg_user_cohorts_updated_at ON public.user_cohorts;
CREATE TRIGGER trg_user_cohorts_updated_at BEFORE UPDATE ON public.user_cohorts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
